### ISSUE TITLE
Multiple label support

### ISSUE THREAD

**Issue by ISSOtm** [KernelEquinox/8F-Helper#1]
Only one label is supported as of now.

Proposition :
`struct Label {
    unsigned int address;
    unsigned int nameLength;
    char* labelName;
};`
with labelName pointing to a calloc'd string.
We next need to have a table of pointers to malloc'd labels that we search through each time we need one.

One label is already nice, but won't fit in some (albeit rare) cases.

**Comment by KernelEquinox** [comment]
Implemented multiple label support with latest commit; I definitely agree on the usefulness of it.
